fix proxy readonly deprecated hooks error in webpack 5
stephencookdev/speed-measure-webpack-plugin pull request #152
Opened 2020-11-26 09:46 UTC by tanhauhau

Fixes https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/149

2020-12-01 03:55 UTC, rmariuzzo requested changes
LGTM, one small change.

2020-12-01 03:55 UTC, rmariuzzo commented on __tests__/setups/v5-deprecated-hooks/package.json
> +  "description": "Test webpack v4 with a StatsPlugin set-up with SMP",
```suggestion
  "description": "Test webpack v5 with a StatsPlugin set-up with SMP",
```

2020-12-09 08:54 UTC, simPod approved these changes

2021-01-21 16:12 UTC, brybrophy commented
@rmariuzzo @simPod Can we get this merged, please? This is blocking my team from being able to upgrade to webpack 5.

2021-01-23 15:50 UTC, stephencookdev commented
Nice, this looks great — awesome stuff @tanhauhau! I'll merge this into the upcoming 1.4.0 release :)

2021-01-23 15:50 UTC, merged